### ISSUE TITLE
Max number of replications

### ISSUE THREAD

**Issue by leannaking** [FIDS-UWO/climate#2]
The maximum number of replications is set to 20, presumably for memory. For smaller numbers of stations, it could be higher.

**Comment by pbreach** [comment]
Just increased the max replications to 9999. I think it would be good to have some kind of warning indicator for higher numbers of replications. Possibly change the numbers to yellow then red or something along those lines.

Better yet, it's possible to reduce memory consumption to close to that of the original files if we write to a file the result of each replication. Leaving this open for time to consider.

**Comment by pbreach** [comment]
Each replication is now saved as it is generated as opposed to accumulating the results. This will reduce memory consumption to that of 1 replication regardless on the number of replications selected.
